// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5KjADgaMXL-pXBWLYlrIJ6Osb_9uYis',
    appId: '1:1064384658921:web:e2afc7de1c855e91491f78',
    messagingSenderId: '1064384658921',
    projectId: 'geekiga-mobile',
    authDomain: 'geekiga-mobile.firebaseapp.com',
    databaseURL:
        'https://geekiga-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geekiga-mobile.appspot.com',
    measurementId: 'G-FS99831M2X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbaCmmOfroWBbBU4v_tXXOPDk6LhMfo7o',
    appId: '1:1064384658921:android:d031845a0b1f781f491f78',
    messagingSenderId: '1064384658921',
    projectId: 'geekiga-mobile',
    databaseURL:
        'https://geekiga-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geekiga-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3IzgLVGJX7Z7HrIgV63lZJwTkB3BKTLM',
    appId: '1:1064384658921:ios:014995c84b86173b491f78',
    messagingSenderId: '1064384658921',
    projectId: 'geekiga-mobile',
    databaseURL:
        'https://geekiga-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geekiga-mobile.appspot.com',
    iosClientId:
        '1064384658921-ncus5pktq3fgca3pvmp80mo6e23dmaml.apps.googleusercontent.com',
    iosBundleId: 'com.example.geekiga',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3IzgLVGJX7Z7HrIgV63lZJwTkB3BKTLM',
    appId: '1:1064384658921:ios:014995c84b86173b491f78',
    messagingSenderId: '1064384658921',
    projectId: 'geekiga-mobile',
    databaseURL:
        'https://geekiga-mobile-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'geekiga-mobile.appspot.com',
    iosClientId:
        '1064384658921-ncus5pktq3fgca3pvmp80mo6e23dmaml.apps.googleusercontent.com',
    iosBundleId: 'com.example.geekiga',
  );
}
